### ISSUE TITLE
d11k-ts package for hermes, dojima chain

### ISSUE THREAD

**Issue by bhaagiKenpachi** [dojimanetwork/d11k-ts#1]

**Comment by yerramreddyuday** [comment]
d11k-ts package for 

1. hermes chain - done
2. dojima chain - In progress

**Comment by yerramreddyuday** [comment]
1. Hermes package - Done

    Commit : [d11k-ts/hermes/d9fbfca](https://github.com/dojimanetwork/d11k-ts/commit/d9fbfca470140f0b41f5ecda59efd762970066de)

2. Dojima package - Done

    Commit : [d11k-ts/dojima/e330a75](https://github.com/dojimanetwork/d11k-ts/commit/e330a75648abba4a5ce2e25986408918f9f3b354)
